# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk Metropolis sampler for generating the standard Laplace distribution using Rcpp
#' @description A random walk Metropolis sampler for generating the standard Laplace distribution using Rcpp
#' @param sigma The standard deviation of proposal distribution N(Xt,sigma^2)
#' @param X0  initial value X0
#' @param N the length of the chain
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rwC <- rw.MetropolisC(.5, 25, 2000)
#'  plot(a, rwC$x, type = "s", main = "", xlab = "sigma = 0.5", ylab = "x")
#' }
#' @export
rwMetropolisC <- function(sigma, x0, N) {
    .Call('_SC19023_rwMetropolisC', PACKAGE = 'SC19023', sigma, x0, N)
}

